### ISSUE TITLE
Implement `attribute_5` (splash)

### ISSUE THREAD

**Issue by j-wielg** [Open-Source-Software-Development/Cardtorium#58]
Write logic for the splash attribute. After attacking a unit, this attribute should inspect every tile in a 1-tile radius of the enemy which got attacked, and attack every enemy within that radius using half as much attack power as usual. DO NOT call the `.attack` or `.being_attacked` methods in the attribute logic (cards affected by splash damage should not be allowed to counter-attack). The damage calculations should resemble those found in `Classes/troop.gd`

See [here](https://github.com/Open-Source-Software-Development/Cardtorium/wiki/Editing-or-Adding-Attributes) for more info on attributes.

Requirements:
- Code should be located at `Attributes/Troops/Logic/attribute_5.gd`
- Code should contain a comment labeling it as the splash attribute
- Code should not call `Troop.attack` or `Troop.being_attacked` methods

**Comment by mayleenliu** [comment]
This is currently being worked on
