### ISSUE TITLE
Implement `attribute_8` (survivalist)

### ISSUE THREAD

**Issue by j-wielg** [Open-Source-Software-Development/Cardtorium#59]
Implement the survivalist attribute, which removes the movement penalty caused by moving through a forest tile. This can be achieved by overriding the `calc_move_cost` method.

See [here](https://github.com/Open-Source-Software-Development/Cardtorium/wiki/Editing-or-Adding-Attributes) for more info on attributes.

Requirements:
- Code should be located at `Attributes/Troops/Logic/attribute_8.gd`
- Code should contain a comment labeling it as the survivalist attribute

**Comment by AGaylord6** [comment]
I submitted a pull request trying this, let me know how it looks!
